# -*- coding: utf-8 -*-
"""AI Sudoku Solver Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xNI4R7Uspdz5gQWHeE_ZN3prcXpga91G
"""

import time
import copy # Import the copy module for deep copying lists

def is_valid(grid, row, col, num):
    """ Check if placing a number breaks Sudoku rules (Row, Col, 3x3 Box) """
    for i in range(9):
        if grid[row][i] == num:
            return False
    for i in range(9):
        if grid[i][col] == num:
            return False
    start_row, start_col = 3 * (row // 3), 3 * (col // 3)
    for i in range(3):
        for j in range(3):
            if grid[start_row + i][start_col + j] == num:
                return False
    return True

def get_mrv_cell(grid):
    """ Optimized MRV: Returns immediately if a cell has 0 or 1 options. """
    min_options = 10
    best_cell = None
    for r in range(9):
        for c in range(9):
            if grid[r][c] == 0:
                options_count = sum(1 for num in range(1, 10) if is_valid(grid, r, c, num))

                # Hit a dead end? Return immediately to force backtrack!
                if options_count == 0:
                    return (r, c)

                # Found a cell with exactly 1 option? It's the best possible choice.
                if options_count == 1:
                    return (r, c)

                if options_count < min_options:
                    min_options = options_count
                    best_cell = (r, c)
    return best_cell

def solve_sudoku(grid):
    """ Core Backtracking Search algorithm utilizing optimized MRV heuristic """
    cell = get_mrv_cell(grid)
    if not cell:
        return True # Puzzle Solved

    row, col = cell
    for num in range(1, 10):
        if is_valid(grid, row, col, num):
            grid[row][col] = num
            if solve_sudoku(grid):
                return True
            grid[row][col] = 0 # Backtrack
    return False

def print_styled_grid(grid, title="Sudoku Grid"):
    """ A mobile/Colab friendly compact grid display """
    print(f"\n--- {title} ---")
    for r in range(9):
        if r % 3 == 0:
            print("-" * 25)

        row_str = "| "
        for c in range(9):
            val = str(grid[r][c]) if grid[r][c] != 0 else "."
            row_str += val + " "
            if (c + 1) % 3 == 0:
                row_str += "| "
        print(row_str.strip())
    print("-" * 25)

# ==========================================
# Grids Definition
# ==========================================
easy_grid = [
    [0, 0, 0, 2, 6, 0, 7, 0, 1],
    [6, 8, 0, 0, 7, 0, 0, 9, 0],
    [1, 9, 0, 0, 0, 4, 5, 0, 0],
    [8, 2, 0, 1, 0, 0, 0, 4, 0],
    [0, 0, 4, 6, 0, 2, 9, 0, 0],
    [0, 5, 0, 0, 0, 3, 0, 2, 8],
    [0, 0, 9, 3, 0, 0, 0, 7, 4],
    [0, 4, 0, 0, 5, 0, 0, 3, 6],
    [7, 0, 3, 0, 1, 8, 0, 0, 0]
]

medium_grid = [
    [0, 0, 0, 6, 0, 0, 4, 0, 0],
    [7, 0, 0, 0, 0, 3, 6, 0, 0],
    [0, 0, 0, 0, 9, 1, 0, 8, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 5, 0, 1, 8, 0, 0, 0, 3],
    [0, 0, 0, 3, 0, 6, 0, 4, 5],
    [0, 4, 0, 2, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0]
]

hard_grid = [
    [8, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 3, 6, 0, 0, 0, 0, 0],
    [0, 7, 0, 0, 9, 0, 2, 0, 0],
    [0, 5, 0, 0, 0, 7, 0, 0, 0],
    [0, 0, 0, 0, 4, 5, 7, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 3, 0],
    [0, 0, 1, 0, 0, 0, 0, 6, 8],
    [0, 0, 8, 5, 0, 0, 0, 1, 0],
    [0, 9, 0, 0, 0, 0, 4, 0, 0]
]

unsolvable_grid = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 7] # This 7 conflicts with the 7 in col 8
]

evil_grid = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 3, 0, 8, 5],
    [0, 0, 1, 0, 2, 0, 0, 0, 0],
    [0, 0, 0, 5, 0, 7, 0, 0, 0],
    [0, 0, 4, 0, 0, 0, 1, 0, 0],
    [0, 9, 0, 0, 0, 0, 0, 0, 0],
    [5, 0, 0, 0, 0, 0, 0, 7, 3],
    [0, 0, 2, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 4, 0, 0, 0, 9]
]

# ==========================================
# Main Execution Menu
# ==========================================
if __name__ == "__main__":
    original_initial_grid = [
        [5, 3, 0, 0, 7, 0, 0, 0, 0],
        [6, 0, 0, 1, 9, 5, 0, 0, 0],
        [0, 9, 8, 0, 0, 0, 0, 6, 0],
        [8, 0, 0, 0, 6, 0, 0, 0, 3],
        [4, 0, 0, 8, 0, 3, 0, 0, 1],
        [7, 0, 0, 0, 2, 0, 0, 0, 6],
        [0, 6, 0, 0, 0, 0, 2, 8, 0],
        [0, 0, 0, 4, 1, 9, 0, 0, 5],
        [0, 0, 0, 0, 8, 0, 0, 7, 9]
    ]

    print("\n--- Sudoku Solver Menu ---")
    print("1. Easy Grid")
    print("2. Medium Grid")
    print("3. Hard Grid")
    print("4. Unsolvable Grid")
    print("5. Original Grid")
    print("6. Evil Grid")

    while True:
        try:
            choice = int(input("Enter your choice (1-6): "))
            if 1 <= choice <= 6:
                break
            else:
                print("Invalid choice. Please enter a number between 1 and 6.")
        except ValueError:
            print("Invalid input. Please enter a number.")

    selected_grid = []
    grid_name = ""
    if choice == 1:
        selected_grid = copy.deepcopy(easy_grid)
        grid_name = "Easy Grid"
    elif choice == 2:
        selected_grid = copy.deepcopy(medium_grid)
        grid_name = "Medium Grid"
    elif choice == 3:
        selected_grid = copy.deepcopy(hard_grid)
        grid_name = "Hard Grid"
    elif choice == 4:
        selected_grid = copy.deepcopy(unsolvable_grid)
        grid_name = "Unsolvable Grid"
    elif choice == 5:
        selected_grid = copy.deepcopy(original_initial_grid)
        grid_name = "Original Grid"
    elif choice == 6:
        selected_grid = copy.deepcopy(evil_grid)
        grid_name = "Evil Grid"

    print_styled_grid(selected_grid, title=f"Initial Problem ({grid_name})")

    print("\n[AI Agent] Solving using Optimized MRV Backtracking...")
    start_time = time.time()

    if solve_sudoku(selected_grid):
        print_styled_grid(selected_grid, title=f"Final Solution ({grid_name})")
        print(f"\n[Success] Puzzle solved in: {time.time() - start_time:.5f} seconds")
    else:
        print(f"\n[Error] No solution exists for the selected '{grid_name}'.")